#!/bin/bash
# Install: curl -sL .../install | sudo bash
# With params (passed to mbt): curl -sL .../install | sudo bash -s -- -all
set -e
wget -qO /usr/local/bin/mbt https://raw.githubusercontent.com/ang3el7z/mbt/master/scripts/mbt.sh
chmod +x /usr/local/bin/mbt
if [ -e /dev/tty ]; then
  exec mbt "$@" < /dev/tty
else
  echo "Установлено. Запустите: mbt"
fi
